spring.application.name=safework

# Flyway gobierna el esquema.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.modulith.events.jdbc.schema-initialization.enabled=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

management.endpoints.web.exposure.include=health,info,modulith
management.endpoint.health.show-details=when-authorized
